-- Adds three engagement block types: COUNTDOWN, COMPARISON_TABLE, MARQUEE.
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'COUNTDOWN' BEFORE 'FOOTER';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'COMPARISON_TABLE' BEFORE 'FOOTER';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'MARQUEE' BEFORE 'FOOTER';
