ALTER TYPE "FormFieldType" ADD VALUE IF NOT EXISTS 'NUMBER';
ALTER TYPE "FormFieldType" ADD VALUE IF NOT EXISTS 'URL';
ALTER TYPE "FormFieldType" ADD VALUE IF NOT EXISTS 'DATE';
ALTER TYPE "FormFieldType" ADD VALUE IF NOT EXISTS 'RADIO';
ALTER TYPE "FormFieldType" ADD VALUE IF NOT EXISTS 'MULTISELECT';
ALTER TYPE "FormFieldType" ADD VALUE IF NOT EXISTS 'CHECKBOXES';
