ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'PRODUCT_SHOWCASE';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'COURSE_SHOWCASE';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'BLOG_SHOWCASE';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'MEMBERSHIP_SHOWCASE';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'AFFILIATE_CTA';
