import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  BookOpen,
  Building2,
  ClipboardList,
  Code2,
  CreditCard,
  FileText,
  Columns3,
  Grid3x3,
  GalleryHorizontal,
  HelpCircle,
  Image as ImageIcon,
  Images,
  Landmark,
  LayoutTemplate,
  ListOrdered,
  Mail,
  Megaphone,
  Menu,
  Minus,
  MousePointerClick,
  PanelBottom,
  PanelTop,
  Quote,
  Rows3,
  Send,
  ShoppingBag,
  SquareUser,
  Timer,
  TrendingUp,
  Type,
  Video,
  MapPin,
  MessageCircle,
  PanelsTopLeft,
} from "lucide-react";

import {
  blockDataSchemas,
  blockTypes,
  type BlockDataMap,
  type BlockType,
} from "./schema";

export type BlockMeta = {
  type: BlockType;
  label: string;
  description: string;
  icon: LucideIcon;
};

export const BLOCK_REGISTRY: Record<BlockType, BlockMeta> = {
  HEADER: {
    type: "HEADER",
    label: "Header",
    description: "Logo, tautan navigasi, dan tombol aksi utama.",
    icon: PanelTop,
  },
  MENU: {
    type: "MENU",
    label: "Menu",
    description: "Menu navigasi ke halaman atau section penting.",
    icon: Menu,
  },
  HERO: {
    type: "HERO",
    label: "Hero",
    description: "Judul utama, subjudul, dan tombol ajakan.",
    icon: LayoutTemplate,
  },
  TEXT: {
    type: "TEXT",
    label: "Teks",
    description: "Paragraf dengan format teks lengkap.",
    icon: Type,
  },
  CUSTOM_HTML: {
    type: "CUSTOM_HTML",
    label: "HTML kustom",
    description: "Impor HTML, CSS, dan JavaScript dalam sandbox.",
    icon: Code2,
  },
  COLUMNS: {
    type: "COLUMNS",
    label: "Kolom",
    description: "Dua atau tiga kolom teks berdampingan.",
    icon: Columns3,
  },
  IMAGE: {
    type: "IMAGE",
    label: "Gambar",
    description: "Satu gambar dengan keterangan opsional.",
    icon: ImageIcon,
  },
  CTA: {
    type: "CTA",
    label: "Ajakan bertindak",
    description: "Banner fokus dengan satu tombol ajakan.",
    icon: MousePointerClick,
  },
  FEATURE_GRID: {
    type: "FEATURE_GRID",
    label: "Grid fitur",
    description: "Kisi fitur atau manfaat.",
    icon: Grid3x3,
  },
  STATS: {
    type: "STATS",
    label: "Statistik",
    description: "Angka dan capaian penting dalam satu baris.",
    icon: BarChart3,
  },
  STEPS: {
    type: "STEPS",
    label: "Langkah",
    description: "Urutan cara kerja bernomor.",
    icon: ListOrdered,
  },
  PRICING: {
    type: "PRICING",
    label: "Tabel harga",
    description: "Paket harga berdampingan.",
    icon: CreditCard,
  },
  TESTIMONIAL: {
    type: "TESTIMONIAL",
    label: "Testimoni",
    description: "Kutipan pelanggan beserta namanya.",
    icon: Quote,
  },
  LOGOS: {
    type: "LOGOS",
    label: "Deretan logo",
    description: "Logo pelanggan atau mitra dalam satu baris.",
    icon: Building2,
  },
  GALLERY: {
    type: "GALLERY",
    label: "Galeri",
    description: "Kisi gambar.",
    icon: Images,
  },
  IMAGE_SLIDER: {
    type: "IMAGE_SLIDER",
    label: "Slider gambar",
    description: "Carousel gambar yang bisa digeser dan berputar otomatis.",
    icon: GalleryHorizontal,
  },
  VIDEO: {
    type: "VIDEO",
    label: "Video",
    description: "Video YouTube atau Vimeo yang disematkan.",
    icon: Video,
  },
  FAQ: {
    type: "FAQ",
    label: "FAQ",
    description: "Daftar tanya-jawab yang bisa dibuka-tutup.",
    icon: HelpCircle,
  },
  NEWSLETTER: {
    type: "NEWSLETTER",
    label: "Newsletter",
    description: "Formulir pendaftaran email.",
    icon: Send,
  },
  BANNER: {
    type: "BANNER",
    label: "Pengumuman",
    description: "Bilah pengumuman tipis dengan tautan.",
    icon: Megaphone,
  },
  CONTACT_FORM: {
    type: "CONTACT_FORM",
    label: "Form kontak",
    description: "Formulir kontak sederhana.",
    icon: Mail,
  },
  FORM_EMBED: {
    type: "FORM_EMBED",
    label: "Forms",
    description: "Tampilkan form dari dashboard Forms.",
    icon: ClipboardList,
  },
  DIVIDER: {
    type: "DIVIDER",
    label: "Pemisah",
    description: "Jarak kosong atau garis pemisah.",
    icon: Minus,
  },
  PRODUCT_SHOWCASE: {
    type: "PRODUCT_SHOWCASE",
    label: "Produk",
    description: "Tampilkan produk unggulan dan arahkan ke toko.",
    icon: ShoppingBag,
  },
  COURSE_SHOWCASE: {
    type: "COURSE_SHOWCASE",
    label: "Kursus",
    description: "Tampilkan kursus dari katalog pembelajaran.",
    icon: BookOpen,
  },
  BLOG_SHOWCASE: {
    type: "BLOG_SHOWCASE",
    label: "Blog",
    description: "Tampilkan artikel atau konten terbaru.",
    icon: FileText,
  },
  MEMBERSHIP_SHOWCASE: {
    type: "MEMBERSHIP_SHOWCASE",
    label: "Membership",
    description: "Tampilkan paket membership dan benefit.",
    icon: CreditCard,
  },
  AFFILIATE_CTA: {
    type: "AFFILIATE_CTA",
    label: "Afiliasi",
    description: "CTA untuk program affiliate workspace.",
    icon: Landmark,
  },
  BUTTON: {
    type: "BUTTON",
    label: "Tombol",
    description: "Tombol aksi tunggal atau kumpulan tombol seperti link tree.",
    icon: MousePointerClick,
  },
  BIO_PROFILE: {
    type: "BIO_PROFILE",
    label: "Profil bio",
    description: "Profil singkat dengan avatar, bio, sosial media, dan link tree.",
    icon: SquareUser,
  },
  COUNTDOWN: {
    type: "COUNTDOWN",
    label: "Hitung mundur",
    description: "Timer hitung mundur ke tanggal target.",
    icon: Timer,
  },
  COMPARISON_TABLE: {
    type: "COMPARISON_TABLE",
    label: "Perbandingan",
    description: "Tabel perbandingan paket atau fitur.",
    icon: Rows3,
  },
  MARQUEE: {
    type: "MARQUEE",
    label: "Teks berjalan",
    description: "Teks bergerak otomatis untuk keunggulan, pengumuman, atau badge.",
    icon: TrendingUp,
  },
  WHATSAPP_FLOAT: {
    type: "WHATSAPP_FLOAT",
    label: "Tombol WhatsApp",
    description: "Tombol chat WhatsApp yang menempel di pojok layar.",
    icon: MessageCircle,
  },
  MAP: {
    type: "MAP",
    label: "Peta lokasi",
    description: "Peta Google Maps dengan alamat, jam buka, dan petunjuk arah.",
    icon: MapPin,
  },
  TABS: {
    type: "TABS",
    label: "Tab",
    description: "Konten bertab untuk kategori atau segmen yang berbeda.",
    icon: PanelsTopLeft,
  },
  FOOTER: {
    type: "FOOTER",
    label: "Footer",
    description: "Tautan penutup, deskripsi brand, sosial media, dan hak cipta.",
    icon: PanelBottom,
  },
};

export const BLOCK_LIST: BlockMeta[] = blockTypes.map((t) => BLOCK_REGISTRY[t]);

/** Returns a fresh default data object for a block type. */
export function defaultBlockData<T extends BlockType>(
  type: T
): BlockDataMap[T] {
  if (type === "HEADER") {
    return {
      logoText: "My Brand",
      logoUrl: "",
      tagline: "Official site",
      primaryLabel: "Hubungi kami",
      primaryHref: "#contact",
      secondaryLabel: "",
      secondaryHref: "#",
      layout: "left",
      tone: "light",
      width: "wide",
      buttonStyle: "solid",
      sticky: false,
      mobileMenu: true,
      showLogo: true,
      showNav: true,
      showCta: true,
      navItems: [
        { label: "Fitur", href: "#features", description: "", badge: "" },
        { label: "Produk", href: "products", description: "", badge: "" },
        { label: "Harga", href: "#pricing", description: "", badge: "" },
      ],
    } as BlockDataMap[T];
  }
  if (type === "MENU") {
    return {
      eyebrow: "Menu",
      heading: "Arahkan pengunjung ke halaman penting",
      description: "Pilih tujuan utama yang paling sering dibutuhkan pengunjung.",
      layout: "pills",
      tone: "soft",
      width: "wide",
      columns: 3,
      align: "center",
      showHeader: true,
      showDescriptions: false,
      items: [
        { label: "Home", href: "#", description: "Kembali ke awal", badge: "" },
        { label: "Produk", href: "products", description: "Lihat katalog", badge: "" },
        { label: "Kursus", href: "courses", description: "Mulai belajar", badge: "" },
        { label: "Blog", href: "blog", description: "Baca update", badge: "" },
      ],
    } as BlockDataMap[T];
  }
  if (type === "FOOTER") {
    return {
      brand: "My Brand",
      description: "Bangun hubungan dengan pengunjung melalui halaman yang jelas dan mudah diakses.",
      copyright: "All rights reserved.",
      ctaHeading: "",
      ctaDescription: "",
      ctaLabel: "",
      ctaHref: "#",
      layout: "columns",
      tone: "light",
      width: "wide",
      showBrand: true,
      showCopyright: true,
      showSocial: true,
      navItems: [
        { label: "Home", href: "#", description: "", badge: "" },
        { label: "Produk", href: "products", description: "", badge: "" },
        { label: "Kontak", href: "#contact", description: "", badge: "" },
      ],
      socialItems: [
        { label: "Instagram", href: "#", description: "", badge: "" },
        { label: "YouTube", href: "#", description: "", badge: "" },
        { label: "WhatsApp", href: "#", description: "", badge: "" },
      ],
    } as BlockDataMap[T];
  }
  if (type === "BIO_PROFILE") {
    return {
      eyebrow: "Bio link",
      name: "Nama Anda",
      title: "Creator & Founder",
      tagline: "Satu halaman untuk semua link penting.",
      bio: "Perkenalkan brand, tawaran, dan kanal utama Anda dalam tampilan bio yang ringkas dan mudah diklik.",
      location: "Indonesia",
      pronouns: "",
      badge: "Available",
      badgeTone: "success",
      avatarUrl: "",
      avatarAlt: "",
      coverUrl: "",
      coverAlt: "",
      verified: true,
      primaryLabel: "Hubungi saya",
      primaryHref: "#contact",
      secondaryLabel: "Lihat produk",
      secondaryHref: "products",
      showStats: true,
      showSocials: true,
      showLinks: true,
      showCover: false,
      showBadge: true,
      showLocation: true,
      showPronouns: true,
      showPrimaryActions: true,
      showLinkDescriptions: true,
      showLinkMeta: true,
      showLinkBadges: true,
      showLinkThumbnails: true,
      layout: "linktree",
      tone: "light",
      width: "narrow",
      buttonStyle: "solid",
      avatarShape: "circle",
      avatarSize: "lg",
      avatarRing: "light",
      coverHeight: "md",
      profileFrame: "card",
      align: "center",
      socialStyle: "icons",
      socialPlacement: "underBio",
      linkLayout: "featured",
      linkStyle: "outline",
      compact: false,
      socials: [
        { platform: "instagram", label: "", href: "#", ariaLabel: "", openInNewTab: true, noFollow: false },
        { platform: "whatsapp", label: "", href: "#", ariaLabel: "", openInNewTab: true, noFollow: false },
        { platform: "website", label: "", href: "#", ariaLabel: "", openInNewTab: true, noFollow: false },
      ],
      links: [
        {
          label: "Produk terbaru",
          description: "Arahkan pengunjung ke penawaran utama.",
          meta: "Rekomendasi",
          href: "products",
          icon: "shop",
          thumbnail: "",
          badge: "New",
          ariaLabel: "",
          highlighted: true,
          openInNewTab: false,
          noFollow: false,
        },
        {
          label: "Booking konsultasi",
          description: "Jadwalkan sesi atau panggilan singkat.",
          meta: "15 menit",
          href: "#contact",
          icon: "calendar",
          thumbnail: "",
          badge: "",
          ariaLabel: "",
          highlighted: false,
          openInNewTab: false,
          noFollow: false,
        },
        {
          label: "Newsletter",
          description: "Dapatkan update dan insight terbaru.",
          meta: "Gratis",
          href: "#newsletter",
          icon: "mail",
          thumbnail: "",
          badge: "",
          ariaLabel: "",
          highlighted: false,
          openInNewTab: false,
          noFollow: false,
        },
      ],
      stats: [
        { value: "12K", label: "Followers" },
        { value: "320", label: "Posts" },
        { value: "98", label: "Projects" },
      ],
    } as BlockDataMap[T];
  }
  if (type === "PRODUCT_SHOWCASE") {
    return {
      eyebrow: "Katalog",
      heading: "Produk unggulan",
      subheading: "Tampilkan produk terbaik dari katalog toko Anda.",
      buttonLabel: "Lihat semua produk",
      buttonHref: "products",
      ctaLabel: "Lihat produk",
      source: "auto",
      limit: 6,
      columns: 3,
      layout: "featured",
      tone: "light",
      width: "wide",
      imageAspect: "landscape",
      cardStyle: "elevated",
      imageFit: "cover",
      buttonStyle: "solid",
      gap: "normal",
      align: "left",
      highlightFirst: true,
      showImages: true,
      showBadge: true,
      showMeta: true,
      showDetail: true,
      showDescription: true,
      compact: false,
      emptyText: "Produk aktif akan otomatis muncul di sini.",
      items: [
        {
          title: "Produk pilihan",
          description: "Deskripsi singkat produk dan alasan pembeli membutuhkannya.",
          href: "products",
          badge: "Produk",
          meta: "Rp 0",
          detail: "Produk fisik / Stok tersedia",
          imageUrl: "",
        },
      ],
    } as BlockDataMap[T];
  }
  if (type === "COURSE_SHOWCASE") {
    return {
      eyebrow: "Pembelajaran",
      heading: "Kursus pilihan",
      subheading: "Bantu pengunjung menemukan materi yang paling relevan, lengkap dengan harga, jumlah modul, dan peserta.",
      buttonLabel: "Lihat semua kursus",
      buttonHref: "courses",
      ctaLabel: "Mulai belajar",
      source: "auto",
      limit: 6,
      columns: 3,
      layout: "featured",
      tone: "soft",
      width: "wide",
      imageAspect: "landscape",
      cardStyle: "elevated",
      imageFit: "cover",
      buttonStyle: "solid",
      gap: "normal",
      align: "left",
      highlightFirst: true,
      showImages: true,
      showBadge: true,
      showMeta: true,
      showDetail: true,
      showDescription: true,
      compact: false,
      emptyText: "Kursus aktif akan otomatis muncul di sini.",
      items: [
        {
          title: "Kursus pilihan",
          description: "Ringkas manfaat dan hasil yang akan didapat peserta.",
          href: "courses",
          badge: "Kursus",
          meta: "Gratis",
          detail: "4 modul / 18 pelajaran / 120 peserta",
          imageUrl: "",
        },
      ],
    } as BlockDataMap[T];
  }
  if (type === "BLOG_SHOWCASE") {
    return {
      eyebrow: "Blog",
      heading: "Artikel terbaru",
      subheading: "Bagikan insight, update, dan cerita dari blog.",
      buttonLabel: "Baca blog",
      buttonHref: "blog",
      ctaLabel: "Baca artikel",
      source: "auto",
      limit: 6,
      columns: 3,
      layout: "featured",
      tone: "soft",
      width: "wide",
      imageAspect: "landscape",
      cardStyle: "elevated",
      imageFit: "cover",
      buttonStyle: "outline",
      gap: "normal",
      align: "left",
      highlightFirst: true,
      showImages: true,
      showBadge: true,
      showMeta: true,
      showDetail: true,
      showDescription: true,
      compact: false,
      emptyText: "Artikel terbaru akan otomatis muncul di sini.",
      items: [
        {
          title: "Judul artikel",
          description: "Cuplikan singkat artikel untuk menarik pembaca.",
          href: "blog",
          badge: "Blog",
          meta: "Terbaru",
          detail: "Tim editorial / 4 menit baca",
          imageUrl: "",
        },
      ],
    } as BlockDataMap[T];
  }
  if (type === "MEMBERSHIP_SHOWCASE") {
    return {
      eyebrow: "Membership",
      heading: "Paket membership",
      subheading: "Tawarkan akses eksklusif dan benefit berlangganan.",
      buttonLabel: "Lihat membership",
      buttonHref: "memberships",
      ctaLabel: "Lihat benefit",
      source: "auto",
      limit: 6,
      columns: 3,
      layout: "featured",
      tone: "soft",
      width: "wide",
      imageAspect: "landscape",
      cardStyle: "elevated",
      imageFit: "cover",
      buttonStyle: "solid",
      gap: "normal",
      align: "left",
      highlightFirst: true,
      showImages: true,
      showBadge: true,
      showMeta: true,
      showDetail: true,
      showDescription: true,
      compact: false,
      emptyText: "Paket membership aktif akan otomatis muncul di sini.",
      items: [
        {
          title: "Premium",
          description: "Akses konten, komunitas, dan benefit eksklusif.",
          href: "memberships",
          badge: "PREMIUM",
          meta: "Bulanan",
          detail: "30 hari akses / 120 member / Benefit eksklusif",
          imageUrl: "",
        },
      ],
    } as BlockDataMap[T];
  }
  if (type === "AFFILIATE_CTA") {
    return {
      eyebrow: "Program afiliasi",
      heading: "Gabung program afiliasi",
      description:
        "Dapatkan komisi dengan merekomendasikan produk, kursus, atau membership kami.",
      commission: "Komisi hingga 20%",
      payoutLabel: "Payout bulanan",
      cookieLabel: "Atribusi 30 hari",
      proofText: "Cocok untuk kreator, partner, reseller, dan pelanggan loyal.",
      imageUrl: "",
      primaryLabel: "Daftar afiliasi",
      primaryHref: "affiliates",
      secondaryLabel: "Pelajari dulu",
      secondaryHref: "#",
      layout: "split",
      tone: "dark",
      width: "wide",
      buttonStyle: "solid",
      showStats: true,
      showBenefits: true,
      showImage: false,
      compact: false,
      benefits: [
        "Bagikan link referral khusus",
        "Dapatkan komisi dari pembelian yang valid",
        "Pantau referral dan payout dari dashboard",
      ],
    } as BlockDataMap[T];
  }
  if (type === "FORM_EMBED") {
    return {
      eyebrow: "Form",
      heading: "Hubungi kami",
      description: "Isi form berikut dan tim kami akan segera menghubungi Anda.",
      formId: "",
      formSlug: "contact",
      formTitle: "",
      formDescription: "",
      submitLabel: "Kirim",
      successMessage: "Terima kasih! Submission Anda sudah kami terima.",
      emptyText: "Pilih form dari dashboard Forms untuk menampilkannya di sini.",
      closedText: "Form ini sedang ditutup.",
      layout: "card",
      tone: "soft",
      width: "wide",
      align: "center",
      showHeader: true,
      useFormCopy: true,
      isOpen: true,
      fields: [],
    } as unknown as BlockDataMap[T];
  }
  return blockDataSchemas[type].parse({}) as BlockDataMap[T];
}

let counter = 0;
/** Stable-enough client id for builder state / React keys. */
export function newBlockId() {
  counter += 1;
  return `blk_${Date.now().toString(36)}_${counter}`;
}
